name: Build slides.pdf document

on:
  push:
    paths:
      - 'slides/**'
      - '.github/workflows/build_slides.yml'
  pull_request:
    branches:
      - 'current'
      - 'future/**'

jobs:

  build_slides:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref_name == 'current' || startsWith(github.ref_name, 'future/')
    permissions: write-all
    steps:

      - name: Initialize
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: kostrykin/build-latex-document-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: slides
          document_filename: slides.pdf
          sources: slides.tex
          latexmk_use_xelatex: true
